#%RAML 1.0 DataType
            type: string
            pattern: '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$'
            description: Date of Birth in YYYY-MM-DD format
            example: "1996-09-27"