#%RAML 1.0 Trait
headers:
      account-number:
        type: string
        description: unique personal id of account
        pattern: '^[A-Z]{4}\d{12,}$'
        required: true
        example: ETSI2833783937292